version: "3.5"
services:
  axitare-video-poc-ingress:
    container_name: axitare-video-poc-ingress
    image: nginx:1.17-alpine
    restart: unless-stopped
    networks:
      - default
    ports:
      - "5601:80"
    volumes:
      - "./docker-nginx.conf:/etc/nginx/nginx.conf:delegated"
  axitare-video-poc-client:
    container_name: axitare-video-poc-client
    build:
      context: ./client
    restart: unless-stopped
    networks:
      - default
    volumes:
      - "./client:/service:delegated"
  axitare-video-poc-server:
    container_name: axitare-video-poc-server
    build:
      context: ./server
    restart: unless-stopped
    ports:
      - 8080
    networks:
      - default
    volumes:
      - "./server:/service:delegated"

networks:
  default:
